kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-devops-pro
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001
        hostPort: 30000
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: control-plane
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
