apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcolor
  labels:
    app: webcolor
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webcolor
  template:
    metadata:
      labels:
        app: webcolor
    spec:
      containers:
        - name: webcolor
          image: kubedevio/web-color:blue
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: webcolor
  labels:
    app: webcolor
spec:
  type: NodePort
  selector:
    app: webcolor # Select the pods with the label app=webcolor
  ports:
    - name: http
      port: 80 # Expose the service on port 80
      targetPort: 80 # Forward traffic to port 80 of the deployment pod
      nodePort: 30000
      protocol: TCP
